### ISSUE TITLE
Is it possible to add support for Chinese?

### ISSUE THREAD

**Issue by plord117** [dominiclet/obsidian-note-definitions#10]
It's impossible to define a Chinese right now

**Comment by plord117** [comment]
> Sure, I'll add this in a later release!

Thanks a lot, it's a Very interesting plugin and I hope it keeps getting better

**Comment by chenxin0397** [comment]
我也非常期待这个插件能支持中文，这样可以帮助我整理更新很多专业术语，希望开发者早日改进！！

**Comment by dominiclet** [comment]
Added support for Chinese characters in 0.3.0
