### ISSUE TITLE
Support defining multiple words in one go

### ISSUE THREAD

**Issue by nilarkian** [dominiclet/obsidian-note-definitions#11]
for example the word **search cost** , even being able to do something **search-cost** will be awesome 

this a great plugin btw, thanks for everything

**Comment by KennyDenvers** [comment]
Thanks for the plugin! I am interested also in using "multiple word expressions". Thought they could be used when put in quotation marks. Would that be an option?

**Comment by dominiclet** [comment]
@KennyDenvers I think preferably multi-word expressions should still work without any additional syntax such as placing them in quotation marks. I'll come up with a solution and update this thread once I'm done!

**Comment by dominiclet** [comment]
Implemented in 0.2.0. Let me know if there are any issues!
