### ISSUE TITLE
Allow definitions to be sourced by their aliases

### ISSUE THREAD

**Issue by MDRUK** [dominiclet/obsidian-note-definitions#12]
Loving the plugin.

I have a newly build theology zettlekaston, so definitions are a big thing. I can't though get alias to work. Here's what I've got:

# Philosophy
*thought, wisdom*
Definition of Philosophy. This definition can span several lines.
It will end when the delimiter is reached.

**Comment by dominiclet** [comment]
Hi, glad you love the plugin. Could you elaborate more on what you mean? I've tested the example you gave, it seems to work fine:
![image](https://github.com/dominiclet/obsidian-note-definitions/assets/58429250/a3497d1e-4fc9-410e-9b45-5fb9f8e3a62f)

**Comment by MDRUK** [comment]
Thanks fore the reply 😊

The problem is that alias are not connecting to the definition word.

The main definitions are connecting fine.

**Comment by MDRUK** [comment]
Ok, that makes sense now 😊 Thanks On 2 Jun 2024, at 05:51, dominiclet ***@***.***> wrote:﻿
Ah I get what you mean, this isn't implemented yet, I'll add it in a later release!

**Comment by dominiclet** [comment]
Implemented in 0.5.0
