### ISSUE TITLE
Some issues for Chinese

### ISSUE THREAD

**Issue by emisjerry** [dominiclet/obsidian-note-definitions#16]
Hi, 

Here are my test(using v0.4.0), something wrong for Chinese:

![image](https://github.com/dominiclet/obsidian-note-definitions/assets/131511/4f5fdbce-3f8d-4ce1-b681-fe5260077147)

```
Example1: WhatIsPUA 、CCR
範例2: Same Energy metaverse SPF SRS  // Starts with Chinese, detection failed
Example2: Same Energy metaverse SPF SRS  // Starts with English, detection succeed

Example2: Same Energy 元宇宙 metaverse SPF SRS  // Contains Chinese, some detection failed
```

**Comment by dominiclet** [comment]
Hi @emisjerry, thanks for bringing this up. At the moment, if a line contains any Chinese characters, the whole line will be treated (and parsed) as Chinese. So mixing English and Chinese in the same line will be problematic at the moment. But I'll look into solving this issue!

**Comment by dominiclet** [comment]
Improved definition search in 0.6.0. Both Chinese and English definitions can now be detected in the same line.
