### ISSUE TITLE
Hover/Underline does not work with non-latin symbols

### ISSUE THREAD

**Issue by vkhatuntsevv** [dominiclet/obsidian-note-definitions#17]
Hi, i work primarily in Russian language, and i noticed that the word is underlined only in English. not only that, i still can RMB and "Preview definition", but the hover does not work on such words. i wonder why can it not be underlined for any other text which fits PHRASE word? it also does not work with symbols like numbers

thanks in advance!

**Comment by dominiclet** [comment]
Hi! Cyrillic characters won't work at the moment. I originally only considered latin characters when writing this, but am currently looking at improving it to be a bit more general. I'll keep you updated on the progress!

**Comment by dominiclet** [comment]
@vkhatuntsevv I've updated the search algorithm in 0.6.0, which should work for non-latin characters. A simple test with Cyrillic characters seem to work as well. 
![image](https://github.com/dominiclet/obsidian-note-definitions/assets/58429250/9cdee776-3c4a-4910-92ab-1162a64e002b)
I'll close this issue, but do let me know if there are still issues when using with Russian language.

**Comment by vkhatuntsevv** [comment]
wow, this was fast! thank you so much! right now everything works perfect!
