### ISSUE TITLE
Unable to use in Reading View

### ISSUE THREAD

**Issue by Riven53** [dominiclet/obsidian-note-definitions#2]
The plugin does not work in reading view

**Comment by FootPrintStudio** [comment]
Hope to see this addressed soon, since I don't see much use for it otherwise; however, I'm very happy to find the plugin regardless, it's something I've been wanting for a while.

**Comment by dominiclet** [comment]
I'll start working on implementing this. Should be able to update this within the week.

**Comment by plord117** [comment]
> I'll start working on implementing this. Should be able to update this within the week.

really appreciate❤️

**Comment by dominiclet** [comment]
Implemented in 0.7.0. Do let me know if you find any issues!
