### ISSUE TITLE
Thank you and a big please.

### ISSUE THREAD

**Issue by nanjingman** [dominiclet/obsidian-note-definitions#20]
If a definited word included among a definited phrase,  all the definitions lost. e.g. "problem” in “creative problem solving”. 
plus: please delimited the number of words in a phrase.
Thank you!

**Comment by dominiclet** [comment]
Hi! Thanks for bringing up this issue! I'm currently working on improving the search algorithm for matching defined words/phrases, which will fix the issue you mentioned. It will also allow me to remove the limitation on the number of words in a phrase. This will be done in the upcoming release.

**Comment by nanjingman** [comment]
Maybe you can use this logic: longer is all. E.g. just mark “creative problem solving”, and neglect other possible definitions in it.

**Comment by dominiclet** [comment]
Fixed the issues you mentioned in 0.6.0. All words should be detected even if they appear within a defined phrase. I'll close this issue, but please let me know if you still encounter any issues with this!

**Comment by nanjingman** [comment]
Great improvment!
