### ISSUE TITLE
Add a newline character to the plugin view

### ISSUE THREAD

**Issue by plord117** [dominiclet/obsidian-note-definitions#21]
There's a newline character in the original definition between two paragrah(see also img 1), But the newline character is not displayed in the plugin view(img2).Is there a solution for this？

<img width="744" alt="image" src="https://github.com/dominiclet/obsidian-note-definitions/assets/103809695/69e90702-fa49-4fdf-8db8-026e76009fbe">

<img width="513" alt="image" src="https://github.com/dominiclet/obsidian-note-definitions/assets/103809695/9ab138ea-1f52-434a-a221-23037464cd85">

**Comment by dominiclet** [comment]
Thanks for highlighting this, I'll work on a fix!
