### ISSUE TITLE
Option to show on click instead of hover

### ISSUE THREAD

**Issue by Riven53** [dominiclet/obsidian-note-definitions#23]
Great plugin but it would be nice if there was a toggle option for showing the popup on click

![image](https://github.com/dominiclet/obsidian-note-definitions/assets/65272120/be242503-7dc8-4296-80e4-2bdaf71e52e3)

This pop up on click would be nice in reading view, in my device as of now clicking on the word while reading does not show the popup (I'm using a tablet)

**Comment by dominiclet** [comment]
That's a good idea! I'll add that option in a subsequent release.
As for mobile support, it is not enabled at the moment as I've yet to test the plugin on mobile, but I plan to add that in the future.

**Comment by dominiclet** [comment]
Implemented in 0.10.0
