### ISSUE TITLE
Conflict with native Callouts

### ISSUE THREAD

**Issue by dmantisk** [dominiclet/obsidian-note-definitions#24]
Obsidian's native callouts allows customizing them so that they can be collapsed/expanded
If the title or content of the callout has a word with a definition, then the expand/collapse won't work in either editing or reading mode.
Clicking it simply shows the source in edit mode, and does nothing in reading mode.

If I disable the "Enable in Reading view" toggle it works, but since the contents are rendered as being in reading view (my assumption) the popup won't work within the callout

**Comment by dominiclet** [comment]
I'll look into this, thanks!

**Comment by nyssance** [comment]
And if title/content include definitions word, natvie callout will lost it's icon.

**Comment by dominiclet** [comment]
Fixed in 0.9.0.
