### ISSUE TITLE
Unable to scroll and render tables

### ISSUE THREAD

**Issue by DanShui-Yu** [dominiclet/obsidian-note-definitions#26]
It is hoped that these two features can be supported.

**Comment by dominiclet** [comment]
Hi, could you elaborate more on what you mean? Are you facing issues with tables in the definition popover?

**Comment by plord117** [comment]
> It is hoped that these two features can be supported.

I just submit a new issue about these two features.
[scroll and img](https://github.com/dominiclet/obsidian-note-definitions/issues/35)

**Comment by dominiclet** [comment]
Superceded by #35
