### ISSUE TITLE
Low Priority : Wikilinks don't work in definition popup (Markdown links work)

### ISSUE THREAD

**Issue by dmantisk** [dominiclet/obsidian-note-definitions#27]
Currently markdown links (`[text](link)`) work inside the popups, but not wikilinks (`[[text]]`)

As there's an easy workaround this is not a big issue

Edit : Only markdown links using obsidian url works.
It seems if you auto generated links don't work in the definition window even if they are markdown links.
You have to manually create the markdown link using the obsidian url.
Like [text](obsidian url)

An auto generated markdown link looks like
`[text](note.md)`
while a link using obsidian url looks like
`[text](obsidian://open?vault=vault_name&file=folder%2Fnote)`

**Comment by dominiclet** [comment]
Thanks for bringing this up. I noticed this too. Not sure why it happens, but I'll look into it.

**Comment by Moyf** [comment]
![image](https://github.com/dominiclet/obsidian-note-definitions/assets/4013062/b3f8f2a1-2b28-4955-95e9-566652b99a48)

It's strange that even when I use the Markdown link format, the links are still not clickable for me. 
(I also can't see the Note Preview by pressing `Ctrl` and hover.)

**Comment by dmantisk** [comment]
> It's strange that even when I use the Markdown link format, the links are still not clickable for me. (I also can't see the Note Preview by pressing `Ctrl` and hover.)
Markdown links don't support note preview (the popup window).

> Maybe it's because I'm using the "Shortest link" ? 🤔
That's not it. It seems if you auto generated links don't work in the definition window even if they are markdown links.
You have to manually create the markdown link using the obsidian url. 
Like `[text](obsidian url)`

**Comment by dominiclet** [comment]
Hi, managed to resolve this issue with a workaround, released in 0.16.1. You can give it a try. I'll keep this issue open for awhile, let me know if there's still any problems with this.

**Comment by dmantisk** [comment]
I can confirm that wiki links are working.
Markdown links (`[text](note)`) don't work, but that's not an issue for me.

**Comment by dominiclet** [comment]
Thanks for confirming, do you have an example for markdown links not working? I tried on my end it seems to work fine.

**Comment by dmantisk** [comment]
Markdown links like `[text](obsidian://open?vault=vault_name&file=folder%2Fnote)` works. (It worked even before)

Markdown links like `[text](note)` still doesn't work

**Comment by dominiclet** [comment]
I've tested that markdown links in the `[text](note)` format works on my end too, is the markdown link that you're testing with valid?

**Comment by FootPrintStudio** [comment]
Not sure if this should be a new issue, but it appears to me it may be related.

Reading view is enabled and I use source mode for editing (I know that causes issues with some plugins). To be fair, it is a bit of a setup in my instance.

This is all the same links.

The red highlighted text is where it breaks a link, this is within an Admonition code block, within an Obsidian Columns code block.
The blue highlighted text is only within an Obsidian Columns code block.
The yellow highlighted text is only within an Admonition code block.
The black highlighted text isn't in any code block, just for reference.

![image](https://github.com/user-attachments/assets/ad2823cd-1859-4b8c-9062-4a3908431fe5)

**Comment by dmantisk** [comment]
> I've tested that markdown links in the `[text](note)` format works on my end too, is the markdown link that you're testing with valid?

It works now. Might have been an issue on my end.
Sorry for the late reply, my account was hacked and I forgot about this after I regained access.

I'd close the issue, but I don't know if the previous comment is related or not

**Comment by christopherjsmith** [comment]
@FootPrintStudio Do you have an example that demonstrates this in MD form? I tried to replicate with no success:

![image](https://github.com/user-attachments/assets/0ed65b21-f219-4def-b190-40b74aa670e1)
![image](https://github.com/user-attachments/assets/b2076f82-1980-43d5-8e05-cd849536de8d)

**Comment by FootPrintStudio** [comment]
I can't replicate the issue either anymore, hopefully, that means that somewhere along the way one of the conflicting plugins' updates solved it.
