### ISSUE TITLE
Phrases containing a word with its own definition generates popups for the phrase & the word

### ISSUE THREAD

**Issue by dmantisk** [dominiclet/obsidian-note-definitions#28]
If there's definition for the work `test` and a definition for the phrase `phrase test`, when you type 'phrase test' somewhere you get the popup for `phrase test` when hovering over the word 'phrase' and another popup for `test` when hovering over 'test'.

The solution would be to have a system where multi word definitions exclude any definitions for words contained inside them.
I'm not a programmer though

**Comment by dominiclet** [comment]
Yeah this is something I wasn't too sure if I should just preserve the current behaviour or handle it as you suggested. But now that you mentioned it, I will adopt your suggestion. Thanks!

**Comment by dominiclet** [comment]
Fixed in 0.9.0
