### ISSUE TITLE
Good job! I look forward to being able to edit within the pop-up window by double click。

### ISSUE THREAD

**Issue by nanjingman** [dominiclet/obsidian-note-definitions#32]
Good job! I look forward to being able to edit within the pop-up window by double click。

**Comment by nanjingman** [comment]
Now, I add a tag page for the term file, and can open it directly as follow: 
![image](https://github.com/dominiclet/obsidian-note-definitions/assets/101070393/05b34e34-a2f7-41d7-8ca6-ca88c0b298b9)

**Comment by nanjingman** [comment]
But I still hope you can add this function. Thanks!

**Comment by dominiclet** [comment]
Editing/adding definitions directly without leaving the current file is something I wish to implement as well. I'll look into this feature after completing some of the higher priority issues!

**Comment by nanjingman** [comment]
now I have implemented this through Quickadd as follow: 

![Uploading image.png…]()

**Comment by nanjingman** [comment]
![image](https://github.com/dominiclet/obsidian-note-definitions/assets/101070393/022674af-dbad-4f5a-9271-da83974829d4)

**Comment by dominiclet** [comment]
I've added an edit modal which can be accessed via 'Right-click on definition' > 'Edit definition'. At the moment, the contents in the modal are displayed in plaintext (and not rendered in markdown) as the Obsidian doesn't seem to expose an API for that, and although possible, as seen from the Hover Editor plugin you mentioned, it does not seem to be trivial to implement. Hence, the edit modal will show the definition as plaintext for now.

**Comment by nanjingman** [comment]
Thank you so! Good!

**Comment by dominiclet** [comment]
Add new definition is now also implemented (0.14.0), instructions can be found in the README.

**Comment by nanjingman** [comment]
A milestone improvement！！
