### ISSUE TITLE
[FR] Compitable with `___` underlines divider

### ISSUE THREAD

**Issue by Moyf** [dominiclet/obsidian-note-definitions#33]
Due to the possibility of the `---` being interpreted as the "Header" syntax in certain contexts, I prefer to use `___` instead of `---`. 
![cf57679a-901d-44f4-9077-30b7b307bd02](https://github.com/dominiclet/obsidian-note-definitions/assets/4013062/909ee7fb-ba10-448c-ad4d-e173a6f06327)

I am curious if this plugin can also recognize `___` as a separator. 
And it's a nice plugin, thanks for developing! <3

**Comment by dominiclet** [comment]
Glad you like the plugin! This is definitely doable, I'll add an option to customise the syntax here.

**Comment by Moyf** [comment]
> Glad you like the plugin! This is definitely doable, I'll add an option to customise the syntax here.

Thanks! 🥳

**Comment by dominiclet** [comment]
Hi, I've implemented this in 0.11.0, you can look for the configuration within the plugin settings. You should see a "Definition file format settings". You can turn toggle the option to use underscore as a divider there.

**Comment by Moyf** [comment]
> Hi, I've implemented this in 0.11.0, you can look for the configuration within the plugin settings. You should see a "Definition file format settings". You can turn toggle the option to use underscore as a divider there.

Wow that's great!
Have updated and it works well, thanks!
