### ISSUE TITLE
It looks the new version not well show the longer/est definited terms, and i think show the  longest is better when serval definitions overlapping. 

### ISSUE THREAD

**Issue by nanjingman** [dominiclet/obsidian-note-definitions#34]
It looks the new version not well show the longer/est definited terms, and i think showing the longest is better when serval definitions overlapping. 
E.g. when "career" and "career management*  overlapped,  the former rather the latter showed ( I think in this case showing the longest is better ). In chinese, also likes this. Thanks again！

**Comment by dominiclet** [comment]
Ah yes, that's would probably be better. I'll fix this in a later release!

**Comment by dominiclet** [comment]
Fixed in 0.9.2

**Comment by nanjingman** [comment]
Great! Thanks!
