### ISSUE TITLE
Add a slider to the preview screen

### ISSUE THREAD

**Issue by plord117** [dominiclet/obsidian-note-definitions#35]
I found a problem that if the definition is too long, the display will not be complete. Could you keep the window size unchanged and add a slider, like obsidian note  preview. Also, I wonder if the image size affects the display？Thanks a lot。💜
e.g.
<img width="520" alt="image" src="https://github.com/dominiclet/obsidian-note-definitions/assets/103809695/c1e86b7d-49e0-4040-95d1-9f782ccee0a4">
obsidian note 
<img width="402" alt="image" src="https://github.com/dominiclet/obsidian-note-definitions/assets/103809695/2791384e-68e9-4683-aef6-564a420c4823">

**Comment by dominiclet** [comment]
I see, sure I will make it scrollable if the content is too long. Although, I still feel that for very long notes/definitions, you would be better off relying on obsidian's built-in file link functionality, which also allows you to preview the note. 

As for your other question, what do you mean by image size affecting the display?

**Comment by jkjoker** [comment]
> 我明白了，如果内容太长，我肯定会让它可滚动。虽然，我仍然觉得对于很长的注释/定义，您最好依靠黑曜石的内置文件链接功能，该功能还允许您预览注释。
> 
> 至于您的另一个问题，您所说的图像大小影响显示是什么意思？

正好想提出这个问题。
问题在于，这个插件提供了一种新的玩法，很有拓展性——比如，我们在文档中自定义的内容，未必是一个单词，而可能是一件事，而这件事，理论上讲，可能会不断得到补充，因此其定义注定会变得很长，所以在预览窗口中添加滚动条确实是很需要的。
相对应的，当我们不局限于只是定义一个单词，那么，在预览状态下（pop状态下）如果也能进行编辑，那就更完美了。

**Comment by dominiclet** [comment]
> 那么，在预览状态下（pop状态下）如果也能进行编辑，那就更完美了。

@jkjoker This is a good suggestion and I'll implement it at a later stage.

**Comment by dominiclet** [comment]
I've added scrolling in 0.11.0, do let me know if you face any issues.
