### ISSUE TITLE
Define Display error

### ISSUE THREAD

**Issue by plord117** [dominiclet/obsidian-note-definitions#36]
If the definition is followed by a symbol, it cannot be recognized
e.g.
without a space
<img width="736" alt="image" src="https://github.com/dominiclet/obsidian-note-definitions/assets/103809695/886f6505-d64a-4dc1-bbcd-fae1b49ee6eb">
Adding a space
<img width="761" alt="image" src="https://github.com/dominiclet/obsidian-note-definitions/assets/103809695/a7669c17-7e75-42a8-a0f9-471b784b3fb5">

**Comment by dominiclet** [comment]
Thanks for highlighting this, I"ll look into it

**Comment by dominiclet** [comment]
Fixed in 0.9.2
