### ISSUE TITLE
Mobile Support - 支持手机端

### ISSUE THREAD

**Issue by jkjoker** [dominiclet/obsidian-note-definitions#37]
如题，期待能同时在手机端使用，毕竟，手机端天然就适合随时随地编辑和完善内容。谢谢~

**Comment by dominiclet** [comment]
Yup I understand, will support mobile as soon as I get the time to test it properly

**Comment by dominiclet** [comment]
Mobile support has been added in 0.15.0.

**Comment by jkjoker** [comment]
> Mobile support has been added in 0.15.0.

非常喜欢，谢谢！
