### ISSUE TITLE
Not support Chinese and English mixed input, especially punctuation

### ISSUE THREAD

**Issue by xjxl520303** [dominiclet/obsidian-note-definitions#38]
中文语句后。Templater 前没有空格。❌
中文语句后。 Templater 前没有空格。✔

中文括号（Templater）❌
中文括号（ Templater ）✔

插件：Templater ❌
插件： Templater ✔
插件:Templater ✔
插件 Templater。❌
插件 Templater 。✔

乔布斯那句话是怎么说的？「Templater」❌
乔布斯那句话是怎么说的？「 Templater 」✔

**Comment by xjxl520303** [comment]
![image](https://github.com/dominiclet/obsidian-note-definitions/assets/53321551/0adc81bc-cc19-4271-9d86-8500b4902a24)

**Comment by dominiclet** [comment]
Hi, can I check which version you are using? If your plugin is not updated, you can try updating and see if it solves the issues mentioned. This should be fixed in 0.9.2, see issue #36

**Comment by dominiclet** [comment]
Closed for inactivity

**Comment by xjxl520303** [comment]
> Hi, can I check which version you are using? If your plugin is not updated, you can try updating and see if it solves the issues mentioned. This should be fixed in 0.9.2, see issue #36

Tky, but I found if the definitions words followed "。", it not working, but instead of "，" or "；" works well.

**Comment by dominiclet** [comment]
Thanks for bringing this up, i'll fix that in a bit.

**Comment by dominiclet** [comment]
Fixed the issue you mentioned in 0.12.0

**Comment by xjxl520303** [comment]
@dominiclet Sorry, I found we were missing a Chinese symbol `？` case, like:

```
中文语句问号后？Templater 不显示定义。
```
