### ISSUE TITLE
A minor bug

### ISSUE THREAD

**Issue by nanjingman** [dominiclet/obsidian-note-definitions#39]
![image](https://github.com/dominiclet/obsidian-note-definitions/assets/101070393/8ccf213f-f593-4606-8ec4-ef9f3ee75e42)

**Comment by nanjingman** [comment]
The latter did not display normally, and hope to solve the problem like this.

**Comment by nanjingman** [comment]
The latter did not display normally, and hope to solve the problems like this.

**Comment by nanjingman** [comment]
Thank you! It looks like there's no problem now. 
![image](https://github.com/dominiclet/obsidian-note-definitions/assets/101070393/ac28f02c-2cd8-4d98-98ec-cab4fc65eb87)

**Comment by dominiclet** [comment]
Great!
