### ISSUE TITLE
'Go to definition' & 'Preview definition' commands not working

### ISSUE THREAD

**Issue by dmantisk** [dominiclet/obsidian-note-definitions#41]
Both the commands are not working either from the command palette or shortcut.

I last remember testing/using these when I first installed it (0.5?), so not sure when things changed.

Maybe I'm having a false memory, but I remember there also being an option to go to the definition in the context menu that's no longer present.

**Comment by dominiclet** [comment]
There seems to be some issues with it, I'll look into fixing this

**Comment by dominiclet** [comment]
I've released a fix for this in 0.10.1, please let me know if you still face any issues with this
