### ISSUE TITLE
Title of definition page

### ISSUE THREAD

**Issue by aikruger** [dominiclet/obsidian-note-definitions#44]
It would be really helpful to have title of the note in which the definition is indicated listed in the popup, in this way I can create several pages with specific glossaries and know which glossary this word is defined in. But an excellent plug-in very helpful

"Here is the definition of the word moused over" -glossary1

**Comment by dominiclet** [comment]
Sure, that's doable, will add that in a future release

**Comment by dominiclet** [comment]
This is implemented in 0.16.0 and can be toggled in the settings.
