### ISSUE TITLE
Unnable to install latest version

### ISSUE THREAD

**Issue by RodWarrior** [dominiclet/obsidian-note-definitions#46]
Hello. I'm gettin "error to install note definitions" on obsidian after latest update. I first tried to update and it failed. Then i tried uninstalling, but i get the same error and can't install again. Obsidian 1.63 with latest installer version.

**Comment by dominiclet** [comment]
That's odd, I've tested it on v1.6.3 Obsidian and the update was successful. Which platform are you on?
