### ISSUE TITLE
Features: note default behavior + size of the pop-up

### ISSUE THREAD

**Issue by TjeerdA** [dominiclet/obsidian-note-definitions#50]
I like the plugin. 

I can think of a few rather simple (I expect) features that would help me and others. 

1) Switching the plugin on/off on a per-file basis. Probably with a global default (off unless otherwise specified or on unless specified)

2) the ability to use specific definition files in a Note (can be combined with the previous feature)

3) to change the scale/size of the pop-up. I find the defaults too big. 

Thanks for considering. 

Best, 

Tjeerd

**Comment by dominiclet** [comment]
Hi, yes for 1 and 2, you can follow issue #45, I will likely go with your suggestion of a per-file selection of definitions. For 3, that's doable too, I'll look into that. In the meantime, you could try manually altering the max-width and max-height of the  definition-popover class in `styles.css` to override the default behaviour and change it to your desired size. Just make sure to add the `!important` tag to make them take precedence.

**Comment by dominiclet** [comment]
Added a configuration to override size of popover in 0.19.0
