### ISSUE TITLE
Handling links better / option to not show aliases

### ISSUE THREAD

**Issue by Aetherinox** [dominiclet/obsidian-note-definitions#51]
I created a hover definition, which is also a link. The only way to get the definition to work was to actually paste the entire link in the alias exactly how it shows on the page:

![WfiWjdc3q7](https://github.com/dominiclet/obsidian-note-definitions/assets/118329232/13c6ee31-284b-4ed9-9e9e-3b9d6f5b72dc)

The problem with this is that links that appear in the definition popup are not formatted. It shows the actual markdown code for the link, so one of two options would be awesome.

If I try to add just an alias that is `mysql plugin`, it doesn't recognize it.

1. Definition popup with the ability to render links as a link / clickable
2. Add an option to the settings which disables aliases appearing in the definition popup.

---

Something else I noticed with the popup position. If the word is on the upper half of the screen and you hover, it's alright. The popup shows below the cursor.

But if you have the word on the lower half of the screen, instead of the popup finding some space above the cursor, it puts it right over the cursor.

![smtaVxgkrv](https://github.com/dominiclet/obsidian-note-definitions/assets/118329232/a5f7f3de-e2cd-4b27-b817-fb7bccf496f1)

**Comment by Aetherinox** [comment]
Theme: `Blue Topaz`
Font Size: `14px`
Obsidian: `1.5.12`

---

However, I did set my theme back to default, unloaded my custom CSS files, and disabled all plugins except this definition plugin, which gave me the result:

![Nj75T5AVq7](https://github.com/dominiclet/obsidian-note-definitions/assets/118329232/7489239f-5952-4634-95c2-00fcb1e4b56d)

I also restarted obsidian after turning everything off just to ensure nothing was left behind cached in the program.

**Comment by dominiclet** [comment]
Hmm I tried using the theme you mentioned, as well as setting the font size with varying zoom levels, all seem to work as expected. Perhaps you could test with a fresh vault with no plugins installed and see if the problem persists? It may be possible that some other plugins did not cleanup properly even after disabling, but I can't be sure.

**Comment by Aetherinox** [comment]
Loaded up a fresh sandbox. Dark default theme is all I changed.

![CjHvZl53cU](https://github.com/dominiclet/obsidian-note-definitions/assets/118329232/036dbf29-41f9-4485-ad93-90f01b9844f9)

**Comment by dominiclet** [comment]
Okay I've managed to reproduce this issue. I've been using Obsidian with the "Hidden" window frame style. Using the window frame will cause the popover to mount at a wrong position, likely due to the offset added by the frame. Thanks for bringing this up, I'll open another issue to track this bug.

**Comment by dominiclet** [comment]
I've fixed that bug in the 0.16.2 update, the popover should appear in the correct position for you now.

**Comment by Aetherinox** [comment]
oh, damn. I didn't even think about the fact of me having the window frame showing. I just do that because it makes some of the menu options easier to see.

Appreciate it. I'm a developer and that idea wouldn't even have popped up.

**Comment by dominiclet** [comment]
Ooh thanks for bringing up and debugging the misalignment issue. I'll fix the issue. 

With regards to the popup position, to maximise the space available for the popup, I've made it popup towards the left if the word is beyond 50% of the viewport width. But yes, it probably needs some improvement if it goes into your sidebar file explorer.

**Comment by dominiclet** [comment]
For disabling alias, I'll add an option for it

**Comment by dominiclet** [comment]
Released a fix in **0.17.1**, which should hopefully fix all the positioning issues you mentioned. The definition popover also shouldn't eat into your file explorer anymore.

**Comment by Aetherinox** [comment]
Yeah, that works better. Appreciate all the fixes. Hopefully it'll fix other themes as well, since there's a few themes that enable full-width bars. Would be a pain if there has to be a individual fix for each theme.

![M9Ma6qVAy3](https://github.com/dominiclet/obsidian-note-definitions/assets/118329232/23b9e7fb-c71f-4174-9719-6c8d91279f38)

**Comment by dominiclet** [comment]
Great! No worries. Yeah I hope so too.

**Comment by dominiclet** [comment]
Added the option to hide alias display in 0.18.0.
