### ISSUE TITLE
Definition categorization option

### ISSUE THREAD

**Issue by FREYA265** [dominiclet/obsidian-note-definitions#56]
Hello,
I think it would be incredible if we had a path in the hover denition: definition folder->physical description->hair.

If we could create this, it would allow us to find our way around our own definitions more easily... and why not eventually be able to change the word directly in the hover screen...

Thank you very much for this plugin

**Comment by dominiclet** [comment]
Hi, glad you like the plugin.

For the suggestions you raised, there are existing features that might satisfy them, unless I'm understanding you incorrectly. To find your way to the definition, you can either:
1. Use the "go to definition" command or right click on the defined word and select "go to definition" to quickly open the definition file.
2. In the settings, enable "Display source definition file". This will display the definition file title in the popover.

To quickly edit the definition without leaving the current file, you can right click on the word and select "Edit definition". This will allow you to edit the definition in a popup modal.
