### ISSUE TITLE
Word detection doesn't work when next to other symbols

### ISSUE THREAD

**Issue by sgomez92** [dominiclet/obsidian-note-definitions#6]
The detection for definitions does not work when the word is wrapped around or next to any symbols, for example:

If I make a definition for the word "Potato", whenever the word appears in the following manner, it won't be detected:
- (Potato).
- (Potato something else).
- (Something else Potato).
- Potato!
- Potato?
- Potato.
- Potato, something else.

Seems to not work with anything next to the word, which makes it a bit unusable when writing sentences that use it.

**Comment by dominiclet** [comment]
Thanks for the feedback. I agree that this is a huge problem and will prioritise fixing this.
