### ISSUE TITLE
Loading workspace wrong

### ISSUE THREAD

**Issue by nanjingman** [dominiclet/obsidian-note-definitions#60]
![image](https://github.com/dominiclet/obsidian-note-definitions/assets/101070393/e19cec44-f4d6-4dfc-9139-1eaf7e93143e)

**Comment by pkej** [comment]
I think some more info is needed. What plugins are you using? What are you trying to do? Find the console output and make it available.

**Comment by dominiclet** [comment]
Yes, what @pkej said. More information would be helpful!

**Comment by nanjingman** [comment]
Thanks! There's no problem now.

**Comment by nanjingman** [comment]
PS: This issue originates from conflicting with zotlit after 1.8.1.

**Comment by nanjingman** [comment]
PS: This issue originates from coflicting with Zotlit plugin after 1.8.0.

**Comment by nanjingman** [comment]
PS: This issue originates from coflicting with Zotlit plugin after 0.18.0.

**Comment by dominiclet** [comment]
The conflict causes Obsidian to be stuck in the "Loading workspace" screen?

**Comment by nanjingman** [comment]
Yes, but 0.2.1 ok again!

**Comment by nanjingman** [comment]
Yes, but 0.21.0 ok again!
