### ISSUE TITLE
some little problems

### ISSUE THREAD

**Issue by chenghuang-coder** [dominiclet/obsidian-note-definitions#61]
Hey,

First of all, thx for this great plugin! Il solved my problem of creating a glossary.

But there‘re some little problems:

1. in my pratice, it seems like that the definition folder is no longer required to be in the root folder of the vault, i' ve put it in a subfolder and it works, so plz consider to remove the relevant content in the readme;
2. the term `delimiter` disappear in the option of the plugin inside OB, instead, it uses `divider` to refer to `---` and `___`, plz consider to coordinate.

Thx again!

**Comment by dominiclet** [comment]
Thanks for highlighting these issues, I'll improve the documentation!
