### ISSUE TITLE
Allow folders to be specified in context

### ISSUE THREAD

**Issue by pkej** [dominiclet/obsidian-note-definitions#64]
I write in several languages depending on my audience. I therefore have different defintions files for different languages. I would like to see the possibility to add frontmatter to the definition files:

```md
---
language:
  - no
  - nb
  - nn
---
```
When I then use ´language: no´in another note it would be good to get the definition from the proper language dictionary. As it is now it usually comes from my English dictionary since they are in a sub-folder "English".

**Comment by dominiclet** [comment]
Would the need here be fulfilled by the definition context feature? You can check out the "Definition context" section in the README

**Comment by pkej** [comment]
I will test it out, at a glance the main problem is that the context is file-based, while I want to limit to folders

That said, I guess I can automate my templates to recurse the language directories upon creation.

**Comment by dominiclet** [comment]
I think including folders would be a good addition too, I'll use this issue to track this then

**Comment by pkej** [comment]
That seems to work, I had one snag where I got the English texts all the time, even after adding context, but after restarting Obsidian it seemed to work.

Thanks for the heads up (to be fair it belonged in a tl;dr :P)

**Comment by dominiclet** [comment]
haha, I will see how I can improve the documentation

**Comment by dominiclet** [comment]
This is implemented in 0.22.0
