### ISSUE TITLE
Allow customisation of popover background 

### ISSUE THREAD

**Issue by Riven53** [dominiclet/obsidian-note-definitions#67]
When the popup for definition appears it gets mixed with the text behind it like this

![image](https://github.com/user-attachments/assets/e3899b34-9f0d-4c6a-9fff-1fa340635881)

![image](https://github.com/user-attachments/assets/6018c8b8-f454-4ea3-a57a-edb719bc2e2f)

It only appears properly if the place behind it has a picture or is empty and works normally

![image](https://github.com/user-attachments/assets/3497d105-39d6-454d-9065-6dbbd70d6cef)

This makes it difficult to use when studying because it is always overlapping

But it is still a great plugin.

**Comment by dominiclet** [comment]
This is likely due to the theme you're using, which set the background color to one that is transparent. I guess I can add an option to easily customise the background colour of the popover, but in the meantime, you can solve this by amending the "definition-popover" CSS class.

**Comment by Riven53** [comment]
I use the default theme as of now, what value should I give the
definition-popover class (I'm not very good with css)

**Comment by dominiclet** [comment]
From the root of your vault, you should see a hidden folder `.obsidian`. Enter the folder `.obsidian/plugins/note-definitions`, where you will see the files related to this plugin. You should see a css file `styles.css` among them. Open it and find the `.definition-popover` class. You want to overwrite the `background-color` property, which currently should hold a value of `var(--background-secondary)`. Replace this with any colour you want. For more info on the values you can set you can refer to this https://developer.mozilla.org/en-US/docs/Web/CSS/background-color

**Comment by dominiclet** [comment]
Have you restarted obsidian after changing it?

**Comment by Riven53** [comment]
I did not, but after restarting the plugin stopped working. It isn't underlining the text and clicking also does not work.

**Comment by dominiclet** [comment]
hmm, I'm not sure why that is happening, but for now just do a clean delete and reinstall of the plugin I guess. I'll add a customisation option for the color so you won't have to mess around with the css.

**Comment by dominiclet** [comment]
I've added a customisation option for the popover background colour in 0.24.0, hope it helps.
