### ISSUE TITLE
Please allow  "I" as separators for aliases

### ISSUE THREAD

**Issue by nanjingman** [dominiclet/obsidian-note-definitions#68]
Please allow  "I" as separators for aliases. 
For example, *Knowledge, skills, abilities|KSA|KSAs|KSAOs*.

**Comment by nanjingman** [comment]
Thanks!

**Comment by nanjingman** [comment]
Sorry, I didn't express myself clearly. I mean either "|" or ",".

**Comment by nanjingman** [comment]
"Knowledge, skills, abilities" is a aliase.

**Comment by nanjingman** [comment]
Therefore, it would be best if you could let us define the delimiter ourselves.

**Comment by nanjingman** [comment]
Perhaps others prefer semicolon, etc.

**Comment by nanjingman** [comment]
Thanks!

**Comment by nanjingman** [comment]
Thanks! I think using the "atomic" definition option is already OK!

**Comment by dominiclet** [comment]
I've added support for the pipe symbol in 0.25.0. Unless there are a lot more requests for other symbols (I think there are only so many sensible symbols that can/should be used as delimiters), I won't add a setting to customise it for now.

**Comment by nanjingman** [comment]
Great!
