### ISSUE TITLE
Issues finding the definition file/folder

### ISSUE THREAD

**Issue by Fossu** [dominiclet/obsidian-note-definitions#70]
Version: Obsidian 1.6.7
Problem: Whenever I try to add a new definition, the "Definition file" drop-down is empty (I have a file with def-type: consolidated in the definitions folder). Whenever I try to add an atomic definition, the folder is found but I'm asked to create a definition file, then even if I create a file with def-type: atomic, it's not found.

Anyone encounters similar problems? Maybe the plugin needs an update for 1.6.7?

**Comment by Fossu** [comment]
Hi, thanks for the answer and the plugin. I was able to fix the issue by specifying the first definition manually in the file. After that the command worked just fine.

**Comment by louiss0** [comment]
I ran into a similar problem. Are you using a windows computer by any chance?

**Comment by Mack127444** [comment]
@Fossu, how exactly did you manually specify the first definition in the file? I'm running into the same issue with trying to make a DEF note file for consolidated definitions.

**Comment by louiss0** [comment]
> @Fossu, how exactly did you manually specify the first definition in the file? I'm running into the same issue with trying to make a DEF note file for consolidated definitions.

Go to the file in the set definition folder. Use the command **Note Definitions: Register consolidated Definition file**. Then run the command **Note Definitions: Refresh Definitions**. 


If that doesn't work remember that the default folder for Note Definitions is called `definitions`. To change this find the folder you want to use as the new Definition folder then press **Set as Definition folder**. Then repeat the steps that I said in the first paragraph. 

Every time you set a new definition file you must re-run  **Note Definitions: Refresh Definitions**.

**Comment by Fossu** [comment]
> I ran into a similar problem. Are you using a windows computer by any chance?

I tested it on Linux (NixOS) and Mac, don't know about Windows.

> @Fossu, how exactly did you manually specify the first definition in the file? I'm running into the same issue with trying to make a DEF note file for consolidated definitions.

I did it using the syntax in the README, basically something like:
# manual definition
*aliases of my definition* 
the actual definition

**Comment by cogscides** [comment]
Same for me on Windows. Helped to create consolidated defs and refresh.

**Comment by namikkou** [comment]
I'm having the same problem, except I'm using obsidian on my iPad. I tried doing what others have suggested in this thread but no matter what I do, the option for the destination file doesn't come up.

**Comment by onqun** [comment]
> > I ran into a similar problem. Are you using a windows computer by any chance?
> 
> I tested it on Linux (NixOS) and Mac, don't know about Windows.
> 
> > @Fossu, how exactly did you manually specify the first definition in the file? I'm running into the same issue with trying to make a DEF note file for consolidated definitions.
> 
> I did it using the syntax in the README, basically add something like this to a definitions file: # manual definition *aliases of my definition* the actual definition

this worked for me ty

**Comment by yonatankremer** [comment]
Worked for me. Super cool plugin, but what about the atomics?

**Comment by NathanIJpma** [comment]
Same problem here. Also on windows.

**Comment by GuanFuling** [comment]
Hi, 
I have the same issue. I set a folder as a definition folder. I registered a consolidated definition file but when i try to add a definition i can't see my file even if i refresh the definitions.  My pc is running on windows 10. Im salted, this plugin seems to do what i was searching to do for months lol.

**Comment by GuanFuling** [comment]
Yep I tried what you mentionned earlier. With manual definition, if i set it up as a atomic definition, i can see in my notes the definition when i hover over the word. But for consolidated definition i could not manage to make it work.
So it's already good, thank you for the plugin it gonna help me to build my database for languages. if wa can take off the underline for the words it would be even better for me.

**Comment by Mack127444** [comment]
Super sorry to hear it still wouldn't work with the consolidate definitions, I'm sure if you play around with it a bit more it might work but it may be a weird case that it isn't. Needless to say, if you want to remove the underline from the words I don't think its directly possible in editing mode, but if you want there is a setting to disable it in reading mode in which it won't show the underline.

**Comment by GuanFuling** [comment]
Thank you for your feedback. I will try again.
For the dotted underline if i disable it in reading mode i ca not see the definition anymore right ? I would like to be still able to see it. I think it's possible with a snippet/css code. I will try to figure it out.
