### ISSUE TITLE
使用的外观主题如果是半透明的会导致弹窗的文本重叠-translucent themes can make it difficult to read definition text.

### ISSUE THREAD

**Issue by LeviSmith111** [dominiclet/obsidian-note-definitions#72]
maybe the background of definition tips should set to opaque by default? Under a translucent theme,the background of the tips make the definition text hard to read.
也许改把定义提示的弹窗背景板设置为默认不透明，不然的话看起来就会像底下这个图一样，文本会重叠在一起……

半透明主题的情况下↓↓↓    use a translucent theme
![image](https://github.com/user-attachments/assets/3cba16eb-4a91-417a-a0e7-0592b6acf716)

不透明主题的情况下↓↓↓    use a opaque theme
![image](https://github.com/user-attachments/assets/04da7e11-d780-4ee5-b9cd-82341917b5d4)

**Comment by dominiclet** [comment]
An option to customise the background of the popover is available here if you're using a translucent background theme. 
![image](https://github.com/user-attachments/assets/fc2e7d71-e619-4b34-b5f1-3a9796f75289)

**Comment by LeviSmith111** [comment]
thanks!
