### ISSUE TITLE
[Feature request] ability to hide underlined dots

### ISSUE THREAD

**Issue by kulizivo** [dominiclet/obsidian-note-definitions#76]
i have a way of highlighting important words and would like to be able to hide this ... preferably in reading mode

**Comment by vkhatuntsevv** [comment]
im not sure how to do that particularly in reading mode but

.def-decoration {
text-decoration-line: none;
}

you just need to google how to apply this little part of code specifically to reading mode. im not that big of a brainy in obsidian and css so yeah

**Comment by kulizivo** [comment]
@vkhatuntsevv im not that good with obsidian either but but ill give it a shot

**Comment by kulizivo** [comment]
@vkhatuntsevv OK so i just tried this and it worked out the box... u rock man! Thanx for the help

**Comment by vkhatuntsevv** [comment]
> @vkhatuntsevv OK so i just tried this and it worked out the box... u rock man! Thanx for the help

you're welcome! just the heads up, it will make all definitions "invisible", without underlining. if you want specific files to have the usual line underlining, you'll need to add cssclasses to them like

---
cssclasses: Underline
---

and in that css snippet add extra code like

.Underline .def-decoration {
text-decoration-line: solid;
}

you can change solid to double, dotted, dashed, waved. google "text-decoration-line" and you'll find different styles for that

**Comment by kulizivo** [comment]
@vkhatuntsevv I appreciate the heads up, though i already have a system for highlighting definitions, i mainly use HTML. unless you know a way to add that instead of the  text decoration line. Regardless ill keep all this in mind and see what if i find a style that i really like. Again you keep doing the most and I appreciate you taking time to help me out 🫂.
