### ISSUE TITLE
Definition body is not rendered as markdown

### ISSUE THREAD

**Issue by Suyashtnt** [dominiclet/obsidian-note-definitions#8]
Read the title. Things such as LaTeX (or in my case, typst) aren't rendered correctly

Source definition:
```md
# Hz
*Hertz*
Per second ($s^-1$)
```

Output:
![image](https://github.com/dominiclet/obsidian-note-definitions/assets/45307955/bac12b52-7942-450c-9411-86faf459cdec)

Expected output:
![image](https://github.com/dominiclet/obsidian-note-definitions/assets/45307955/a10e7121-2a9a-4400-9b55-a34c5ada98ce)

**Comment by dominiclet** [comment]
Thanks for the feedback, I'll add support for markdown in a later release.

**Comment by dominiclet** [comment]
Added support for markdown in 0.4.0
