### ISSUE TITLE
Detect plural instances of definitions

### ISSUE THREAD

**Issue by nredick** [dominiclet/obsidian-note-definitions#82]
Would love it if I didn't have to add the plurals to aliases and instead plural definitions were detected automatically.

**Comment by christopherjsmith** [comment]
I quite like this idea, as it's a common use case. My main concern is knowing the language, but there are a couple of options we could consider:

1. Have the use define their language and attempt to pluralise using the ruleset for that language
2. Use auto language detection - probably a limited subset, and will be error prone on single words or small phrases

From a performance perspective it would be a hit at load, as it would mean processing each definition into additional parses. Maybe this could be an option to enable or disable in case people are using large definition sets.

1. Detect language and take highest match with: https://github.com/nitotm/efficient-language-detector-js
2. Generate plural version: https://www.npmjs.com/package/make-plural
3. Add to parse tree

**Comment by nredick** [comment]
I like the idea of being able to turn it on and off--maybe it could just suggest plural aliases that you could add like [+ dogs] as you make the definition or even just have a separate field for adding plural aliases that are hidden by default like aliases: ...; plurals: ...

**Comment by christopherjsmith** [comment]
Unfortunately, after more research it looks like it would be very hard to support any languages other than English. And the English support will also come with mistakes too. That being said, it's still quite handy!

If you are familiar with the BRAT plugin, I recommended installing my pre-release version listed below, to test and provide feedback:

https://github.com/christopherjsmith/obsidian-note-definitions-ipad

**Comment by dominiclet** [comment]
Have merged this in, thanks for the implementation!
